Repository semgrep/semgrep, pull requests merged in 2020-06, with the labels that each got.

#893 Clean up CLI flags
  CHANGELOG.md
  semgrep/semgrep/cli.py
  semgrep/semgrep/semgrep_main.py
  semgrep/semgrep/test.py
Labels: UX, tech debt

#860 Documentation touchups
  docs/configuration-files.md
  docs/pattern-features.md
Labels: documentation

#896 Match '/.../' in generic regex.
  semgrep-core/matching/Generic_vs_generic.ml
  semgrep-core/tests/js/regexp.js
  semgrep-core/tests/js/regexp.sgrep
Labels: external-user, lang:javascript

#932 ci: Run python tests once only
  .github/workflows/tests.yml
Labels: devops

#949 Update README and docs to be more clear and intuitive to new users
  README.md
  docs/README.md
  docs/SUMMARY.md
  docs/configuration-files.md
  docs/pattern-features.md
  semgrep.svg
Labels: documentation

#1074 Document preferring single quotes in YAML
  docs/configuration-files.md
Labels: documentation

#1094 Fix docs typo
  docs/configuration-files.md
Labels: documentation

#1115 Initial draft of rule writing methodology, reference rule docs from README and docs/README
  README.md
  docs/README.md
  docs/writing_rules/README.md
Labels: documentation
