Repository semgrep/semgrep, pull requests merged in 2020-07, with the labels that each got.

#1232 Add Java and Python constant propagation docs
  docs/pattern-features.md
Labels: documentation

#1241 Revise CONTRIBUTING.md and development.md
  CONTRIBUTING.md
  docs/README.md
  docs/development.md
Labels: documentation

#1263 Remove sdist from pypi release
  release-scripts/build-wheels.sh
Labels: devops

#1276 Allow untyped function definitions to match typed definitions
  semgrep-core/matching/Generic_vs_generic.ml
  semgrep-core/tests/python/untyped_vs_typed.py
  semgrep-core/tests/python/untyped_vs_typed.sgrep
Labels: lang:javascript, lang:python

#1321 Include taint-tracking instructions in Experimental
  docs/experimental.md
Labels: documentation

#1357 Move typed metavariables from experimental to official support
  docs/experimental.md
  docs/pattern-features.md
  semgrep-core/tests/generate_test_matrix.py
  semgrep-core/tests/go/metavar_typed.go
  semgrep-core/tests/go/metavar_typed.sgrep
  semgrep-core/tests/go/metavar_typed_args.go
  semgrep-core/tests/go/metavar_typed_args.sgrep
  semgrep-core/tests/go/metavar_typed_fieldaccess.go
  semgrep-core/tests/go/metavar_typed_fieldaccess.sgrep
  semgrep-core/tests/go/metavar_typed_lefthand.go
  semgrep-core/tests/go/metavar_typed_lefthand.sgrep
  semgrep-core/tests/go/typed_comparison.sgrep
  semgrep-core/tests/java/metavar_typed.java
  semgrep-core/tests/java/metavar_typed.sgrep
  semgrep-core/tests/java/metavar_typed_args.java
  semgrep-core/tests/java/metavar_typed_args.sgrep
  semgrep-core/tests/java/metavar_typed_classfield.java
  semgrep-core/tests/java/metavar_typed_classfield.sgrep
  semgrep-core/tests/java/metavar_typed_dot_method.java
  semgrep-core/tests/java/metavar_typed_dot_method.sgrep
  semgrep-core/tests/java/metavar_typed_fieldaccess.java
  semgrep-core/tests/java/metavar_typed_fieldaccess.sgrep
  semgrep-core/tests/java/metavar_typed_function.java
  semgrep-core/tests/java/metavar_typed_function.sgrep
  semgrep-core/tests/java/metavar_typed_if_statement.java
  semgrep-core/tests/java/metavar_typed_if_statement.sgrep
  semgrep-core/tests/java/metavar_typed_lefthand.java
  semgrep-core/tests/java/metavar_typed_lefthand.sgrep
  semgrep-core/tests/java/metavar_typed_localvar.java
  semgrep-core/tests/java/metavar_typed_localvar.sgrep
  semgrep-core/tests/java/metavar_typed_methodcall.java
  semgrep-core/tests/java/metavar_typed_methodcall.sgrep
  semgrep-core/tests/java/typed_comparison.sgrep
Labels: documentation, pattern:types
