Repository semgrep/semgrep, pull requests merged in 2020-05, with the labels that each got.

#610 Add flag for specifying number of subprocesses to use to run checks in parallel
  CHANGELOG.md
  semgrep-core/bin/main_semgrep_core.ml
  semgrep/semgrep/cli.py
  semgrep/semgrep/core_runner.py
  semgrep/semgrep/semgrep_main.py
  semgrep/semgrep/test.py
Labels: blocked

#754 Use git tag for semgrep-core version string
  semgrep-core/Makefile
  semgrep-core/bin/main_semgrep_core.ml
Labels: devops

#755 Add autogenerated version file to gitignore
  .gitignore
Labels: devops

#766 Add stub version.py to appease mypy
  semgrep/semgrep/constants.py
  semgrep/semgrep/version.py
Labels: devops

#783 Fix get_re_matches error with deep paths
  semgrep/semgrep/core_runner.py
  semgrep/tests/e2e/targets/basic/README.md
  semgrep/tests/e2e/targets/basic/bento.png
Labels: bug

#793 Add documentation for metavariable matching
  docs/configuration-files.md
Labels: documentation
