Repository semgrep/semgrep, pull requests merged in 2022-07, with the labels that each got.

#5681 Rename dependencyparser to semdep
  .github/workflows/release.yml
  cli/Pipfile
  cli/Pipfile.lock
  cli/park.cfg
  cli/src/semdep/__init__.py
  cli/src/semdep/find_lockfiles.py
  cli/src/semdep/models.py
  cli/src/semdep/package_restrictions.py
  cli/src/semdep/parse_lockfile.py
  cli/src/semgrep/dependency_aware_rule.py
  cli/src/semgrep/rule.py
  cli/src/semgrep/semgrep_main.py
Labels: wait-for-me

#5719 fix some env vars, convert ssh urls
  changelog.d/cli-267.fixed
  cli/src/semgrep/meta.py
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-bitbucket/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-bitbucket/results.txt
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-buildkite/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-buildkite/results.txt
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-circleci/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-circleci/results.txt
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-bitbucket/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-bitbucket/results.txt
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-buildkite/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-buildkite/results.txt
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-circleci/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-circleci/results.txt
  cli/tests/e2e/test_ci.py
Labels: wait-for-me

#5723 feat(extract): add concatenation reduction
  changelog.d/extract-reductions.added
  cli/src/semgrep/rule_schema.yaml
  semgrep-core/semgrep_extracting.opam
  semgrep-core/src/core/Rule.ml
  semgrep-core/src/engine/Match_extract_mode.ml
  semgrep-core/src/engine/Match_extract_mode.mli
  semgrep-core/src/engine/Test_engine.ml
  semgrep-core/src/engine/Test_engine.mli
  semgrep-core/src/engine/Unit_engine.ml
  semgrep-core/src/extracting/Extract.ml
  semgrep-core/src/extracting/dune
  semgrep-core/src/parsing/Parse_rule.ml
  semgrep-core/src/runner/Run_semgrep.ml
  semgrep-core/src/runner/Run_semgrep.mli
  semgrep-core/src/runner/dune
  semgrep-core/tests/extract/bash_docker.docker
  semgrep-core/tests/extract/bash_docker.yaml
  semgrep-core/tests/extract/bash_python.py
  semgrep-core/tests/extract/bash_python.yaml
  semgrep-core/tests/extract/js_html_concat.html
  semgrep-core/tests/extract/js_html_concat.yaml
Labels: enhancement, feature:extract

#5737 Support taint traces in extract mode
  changelog.d/extract-taint-traces.added
  semgrep-core/src/engine/Match_extract_mode.ml
Labels: feature:taint, feature:extract

#5743 Update indexing to used match based data
  changelog.d/index.fixed
  cli/src/semgrep/rule_match.py
  cli/tests/e2e/snapshots/test_autofix/test_autofix/rulesautofixcsv-writer.yaml-autofixcsv-writer.py-dryrun/results.json
  cli/tests/e2e/snapshots/test_autofix/test_autofix/rulesautofixcsv-writer.yaml-autofixcsv-writer.py-not-dryrun/results.json
  cli/tests/e2e/snapshots/test_autofix/test_autofix/rulesautofixflask-use-jsonify.yaml-autofixflask-use-jsonify.py-dryrun/results.json
  cli/tests/e2e/snapshots/test_autofix/test_autofix/rulesautofixflask-use-jsonify.yaml-autofixflask-use-jsonify.py-not-dryrun/results.json
  cli/tests/e2e/snapshots/test_autofix/test_autofix/rulesautofixjava-string-wrap.yaml-autofixjava-string-wrap.java-dryrun/results.json
  cli/tests/e2e/snapshots/test_autofix/test_autofix/rulesautofixjava-string-wrap.yaml-autofixjava-string-wrap.java-not-dryrun/results.json
  cli/tests/e2e/snapshots/test_autofix/test_autofix/rulesautofixrequests-use-timeout.yaml-autofixrequests-use-timeout.py-dryrun/results.json
  cli/tests/e2e/snapshots/test_autofix/test_autofix/rulesautofixrequests-use-timeout.yaml-autofixrequests-use-timeout.py-not-dryrun/results.json
  cli/tests/e2e/snapshots/test_check/test_deduplication/results.json
  cli/tests/e2e/snapshots/test_check/test_deduplication_different_message/results.json
  cli/tests/e2e/snapshots/test_check/test_metavariable_propagation_comparison/results.json
  cli/tests/e2e/snapshots/test_check/test_multiple_configs_different_origins/results.json
  cli/tests/e2e/snapshots/test_check/test_nested_pattern_either_rule/results.json
  cli/tests/e2e/snapshots/test_check/test_regex_rule__not2/results.json
  cli/tests/e2e/snapshots/test_check/test_regex_rule__pattern_regex_and_pattern_not_regex/results.json
  cli/tests/e2e/snapshots/test_check/test_regex_rule__utf8/results.json
  cli/tests/e2e/snapshots/test_check/test_url_rule/results.json
  cli/tests/e2e/snapshots/test_ci/test_dryrun/results.txt
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-azure-pipelines/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-bitbucket/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-buildkite/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-circleci/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-github-enterprise/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-github-pr/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-github-push/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-gitlab-push/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-gitlab/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-jenkins/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-local/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-travis/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-azure-pipelines/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-bitbucket/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-buildkite/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-circleci/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-github-enterprise/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-github-pr/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-github-push/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-gitlab-push/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-gitlab/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-jenkins/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-local/findings.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-travis/findings.json
  cli/tests/e2e/snapshots/test_dependency_aware_rules/test_dependency_aware_rules/rulesdependency_awareawscli_vuln.yaml-dependency_awareawscli_vuln.py/results.txt
  cli/tests/e2e/snapshots/test_messsage_interpolation/test_message_interpolation/rulesmessage_interpolationmulti-pattern-inside.yaml-message_interpolationmulti_pattern_inside_nested.py/results.json
  cli/tests/e2e/snapshots/test_metavariable_regex_const_prop/test_metavariable_regex_const_prop/results.json
  cli/tests/e2e/snapshots/test_nosemgrep/test_nosem_rule/results.json
  cli/tests/e2e/snapshots/test_nosemgrep/test_nosem_rule__with_disable_nosem/results.json
  cli/tests/e2e/snapshots/test_nosemgrep/test_regex_rule__nosemgrep/results.json
  cli/tests/e2e/snapshots/test_spacegrep/test_spacegrep/rulesspacegrephtml.yaml-spacegrephtml.mustache/results.json
  cli/tests/e2e/snapshots/test_spacegrep/test_spacegrep_nosem/rulesspacegrepnosem-html.yaml-spacegrepnosem.html/results.json
  cli/tests/e2e/test_ci.py
Labels: wait-for-me

#5749 feat(extract): allow `generic` as language
  changelog.d/pa-1648.added
  semgrep-core/src/core/Rule.ml
  semgrep-core/src/engine/Match_extract_mode.ml
  semgrep-core/src/parsing/Parse_rule.ml
Labels: enhancement, feature:extract

#5755 fix(scala): allowed percolation of name information from class parameters
  changelog.d/gh-5506.fixed
  semgrep-core/src/naming/Naming_AST.ml
  semgrep-core/tests/scala/class_params.scala
  semgrep-core/tests/scala/class_params.sgrep
Labels: analysis:naming, lang:scala

#5792 fix: pr templates and small workflow bugs
  .github/PULL_REQUEST_TEMPLATE/release_pr_template.md
  .github/pull_request_template.md
  .github/workflows/start-release.yml
Labels: wait-for-me

#5821 fix(debug): make dump-il more cohesive
  semgrep-core/src/cli/Main.ml
  semgrep-core/src/experiments/datalog/Datalog_experiment.ml
  semgrep-core/src/experiments/datalog/Datalog_experiment.mli
Labels: feature:debug
