Repository semgrep/semgrep, pull requests merged in 2023-11, with the labels that each got.

#9175 Fix wrong default engine type when secret beta is enabled
  changelog.d/ea-248.fixed
  cli/src/semgrep/engine.py
Labels: wait-for-me

#9147 fix(ls): reintroduce #9113
  Makefile
  dune-project
  libs/lwt_platform/Lwt_platform.mli
  libs/lwt_platform/js/Lwt_platform.ml
  libs/lwt_platform/unix/Lwt_platform.ml
  scripts/osx-setup-for-release.sh
  scripts/setup-m1-builder.sh
  semgrep.opam
  src/osemgrep/language_server/LS.ml
  src/osemgrep/language_server/Test_LS_e2e.ml
  src/osemgrep/language_server/Unit_LS.ml
Labels: blocked

#9200 fix: regression in react-nextjs-router-push test
  changelog.d/pa-3089.fixed
  src/analyzing/CFG_build.ml
Labels: wait-for-me

#9223 chore: linecol to bytepos
  languages/yaml/generic/yaml_to_generic.ml
  libs/lib_parsing/Parsing_helpers.ml
  libs/lib_parsing/Pos.ml
  libs/lib_parsing/Pos.mli
  libs/lib_parsing/Tok.mli
  libs/lib_parsing/dune
  scripts/run-core-test
  src/core/Range.ml
  src/engine/Xpattern_matcher.ml
Labels: stacked-diff

#9329 fix: tainting: Do not taint subexpressions of `by-side-effect: only`
  changelog.d/pa-3282.fixed
  src/tainting/Dataflow_tainting.ml
  tests/rules/taint_typestate.py
  tests/rules/taint_typestate2.cpp
  tests/rules/taint_typestate2.yaml
Labels: wait-for-me
