Repository semgrep/semgrep, pull requests merged in 2023-09, with the labels that each got.

#8633 fix: persist full scan diagnostics until change
  changelog.d/pa-3046.fixed
  cli/src/semgrep/lsp/config.py
  cli/src/semgrep/lsp/server.py
  cli/tests/e2e/test_ls.py
  src/osemgrep/language_server/LS.ml
  src/osemgrep/language_server/Session.ml
  src/osemgrep/language_server/Session.mli
Labels: wait-for-me

#8692 fix(ci): semgrep ci --pro defaults to legacy
  cli/bin/semgrep
Labels: wait-for-me

#8693 feat(ls): ignore ci ignored
  changelog.d/lang-server.added
  changelog.d/lang-server.fixed
  libs/networking/Http_mock_client.ml
  libs/networking/Http_mock_client.mli
  src/osemgrep/cli_ci/Ci_subcommand.ml
  src/osemgrep/cli_scan/Output.ml
  src/osemgrep/cli_scan/Output.mli
  src/osemgrep/language_server/Diagnostics.ml
  src/osemgrep/language_server/LS.ml
  src/osemgrep/language_server/Processed_run.ml
  src/osemgrep/language_server/Processed_run.mli
  src/osemgrep/language_server/Session.ml
  src/osemgrep/language_server/Session.mli
  src/osemgrep/language_server/Unit_LS.ml
  src/osemgrep/networking/Scan_helper.ml
  src/osemgrep/networking/Semgrep_App.ml
  src/osemgrep/networking/Semgrep_App.mli
  src/osemgrep/networking/Unit_Login.ml
  src/osemgrep/networking/dune
  src/osemgrep/reporting/Cli_json_output.ml
  src/osemgrep/reporting/Cli_json_output.mli
  src/osemgrep/reporting/dune
  tests/login/ok_response.json
  tests/ls/ci/deployment_conf_resp.json
  tests/ls/ci/request.json
  tests/ls/ci/response.json
  tests/ls/ci/rule_conf_resp.json
Labels: wait-for-me

#8510 feat!: capture group bindings from metavariable-regex
  changelog.d/pa-3011.added
  cli/tests/e2e/snapshots/test_check/test_metavariable_propagation_regex/results.json
  cli/tests/e2e/snapshots/test_check/test_metavariable_regex_rule/results.json
  cli/tests/e2e/snapshots/test_join_rules/test_recursive_join_rules/rulesjoin_rulesrecursivejava-callgraph-examplevulnado-sqli.yaml-join_rulesrecursivejava-callgraph-examplevulnado/results.json
  cli/tests/e2e/snapshots/test_metavariable_regex_const_prop/test_metavariable_regex_const_prop/results.json
  cli/tests/e2e/test_check.py
  cli/tests/e2e/test_metavariable_regex_const_prop.py
  libs/commons/Regexp_engine.ml
  libs/commons/Regexp_engine.mli
  src/engine/Eval_generic.ml
  src/engine/Eval_generic.mli
  src/engine/Match_search_mode.ml
  src/engine/Metavariable_regex.ml
  src/engine/Metavariable_regex.mli
  src/engine/Xpattern_match_regexp.ml
  src/engine/Xpattern_match_regexp.mli
  tests/rules/metavar_regex_capture.py
  tests/rules/metavar_regex_capture.yaml
Labels: stacked-diff

#8845 fix(swift): Address all remaining "not implemented" errors
  changelog.d/swift-parsing.fixed
  languages/swift/generic/Parse_swift_tree_sitter.ml
  libs/lib_parsing/Tok.ml
  libs/lib_parsing/Tok.mli
Labels: wait-for-me

#8856 fix(secrets): permit both CI and scan config IDs
  cli/src/semgrep/config_resolver.py
Labels: wait-for-me

#8866 fix semgrep.js s3 upload for the millionth time
  .github/workflows/build-test-javascript.yaml
Labels: publish-js
