Repository semgrep/semgrep, pull requests merged in 2023-08, with the labels that each got.

#8504 osemgrep: rename __main__.py to simple main.py and remove some shebang
  .github/workflows/tests.yml
  cli/bin/pysemgrep
  cli/bin/semgrep
  cli/setup.py
  cli/src/semgrep/__main__.py
  cli/src/semgrep/cli.py
  cli/src/semgrep/console.py
  cli/src/semgrep/main.py
  scripts/run-benchmarks.sh
Labels: Do not merge

#8517 osemgrep: rename semgrep_main.py to run_scan.py
  changelog.d/internals.changed
  cli/src/semgrep/commands/ci.py
  cli/src/semgrep/commands/scan.py
  cli/src/semgrep/core_runner.py
  cli/src/semgrep/join_rule.py
  cli/src/semgrep/run_scan.py
  cli/src/semgrep/test.py
  cli/tests/e2e/test_api.py
Labels: Do not merge

#8542 ftr(scan): include commit_timestamp in ci
  PRIVACY.md
  changelog.d/cli-timestamp.added
  cli/src/semgrep/meta.py
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-azure-pipelines-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-azure-pipelines/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-bitbucket-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-bitbucket/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-buildkite-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-buildkite/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-circleci-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-circleci/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-github-enterprise/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-github-pr-semgrepconfig/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-github-pr/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-github-push-special-env-vars/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-github-push/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-gitlab-push/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-gitlab-special-env-vars/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-gitlab/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-jenkins-missing-vars/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-jenkins-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-jenkins/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-local/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-self-hosted/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-travis-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-travis/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/autofix-unparsable_url/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-azure-pipelines-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-azure-pipelines/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-bitbucket-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-bitbucket/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-buildkite-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-buildkite/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-circleci-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-circleci/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-github-enterprise/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-github-pr-semgrepconfig/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-github-pr/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-github-push-special-env-vars/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-github-push/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-gitlab-push/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-gitlab-special-env-vars/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-gitlab/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-jenkins-missing-vars/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-jenkins-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-jenkins/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-local/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-self-hosted/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-travis-overwrite-autodetected-variables/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-travis/meta.json
  cli/tests/e2e/snapshots/test_ci/test_full_run/noautofix-unparsable_url/meta.json
  cli/tests/e2e/test_ci.py
Labels: cli

#8557 Bug fix for merging findings
  changelog.d/gh-8557.fixed
  cli/src/semgrep/formatter/text.py
  cli/tests/e2e/rules/cli_test/match_diff_rules_same_msg/src.py
  cli/tests/e2e/rules/cli_test/match_rules_same_message/rules.yml
  cli/tests/e2e/snapshots/test_cli_test/test_cli_test_match_rules_same_message/result.txt
  cli/tests/e2e/snapshots/test_cli_test/test_cli_test_match_rules_same_message/results.txt
  cli/tests/e2e/test_cli_test.py
Labels: wait-for-me

#8558 feat: Temporary CLI UI to display secrets validation.
  cli/src/semgrep/formatter/text.py
Labels: wait-for-me
