Repository semgrep/semgrep, pull requests merged in 2024-04, with the labels that each got.

#9922 feat(lsp): default search to regex
  src/osemgrep/language_server/custom_requests/Search.ml
  src/osemgrep/language_server/custom_requests/Search.mli
  src/osemgrep/language_server/custom_requests/dune
  src/osemgrep/language_server/requests/Request_handler.ml
Labels: stacked-diff

#9930 refactor(lsp): use search env, clean up
  src/osemgrep/language_server/custom_requests/Search.ml
  src/osemgrep/language_server/custom_requests/Search.mli
  src/osemgrep/language_server/custom_requests/dune
  src/osemgrep/language_server/requests/Request_handler.ml
Labels: stacked-diff

#9933 feat(lsp): streaming search
  src/osemgrep/language_server/Test_LS_e2e.ml
  src/osemgrep/language_server/custom_requests/Search.ml
  src/osemgrep/language_server/custom_requests/Search.mli
  src/osemgrep/language_server/requests/Request_handler.ml
  src/osemgrep/language_server/scan_helpers/Scan_helpers.ml
  src/osemgrep/language_server/scan_helpers/Scan_helpers.mli
  src/osemgrep/language_server/server/Search_config.ml
  src/osemgrep/language_server/server/Session.ml
  src/osemgrep/language_server/server/Session.mli
  src/osemgrep/language_server/util/Convert_utils.ml
  src/osemgrep/language_server/util/Convert_utils.mli
Labels: stacked-diff

#9941 chore(lsp): dont search python thrice
  src/osemgrep/language_server/custom_requests/Search.ml
Labels: stacked-diff

#9945 feat(lsp): search with includes/excludes
  libs/git_wrapper/Git_wrapper.ml
  libs/git_wrapper/Git_wrapper.mli
  libs/paths/Ppath.ml
  src/osemgrep/language_server/Test_LS_e2e.ml
  src/osemgrep/language_server/custom_requests/Search.ml
  src/osemgrep/language_server/custom_requests/Search.mli
  src/osemgrep/language_server/custom_requests/dune
  src/osemgrep/language_server/server/Session.ml
Labels: stacked-diff

#9949 feat(lsp): match previews for `/semgrep/search`
  src/osemgrep/language_server/custom_requests/Search.ml
  src/osemgrep/language_server/custom_requests/dune
Labels: stacked-diff

#9979 feat(lsp): multiple pattern search
  src/core/Rule.ml
  src/osemgrep/language_server/custom_requests/Search.ml
  src/osemgrep/networking/Rule_fetching.ml
  src/osemgrep/networking/Rule_fetching.mli
  src/parsing/Parse_rule.ml
  src/parsing/Parse_rule.mli
Labels: stacked-diff

#10130 feature: CLI options for writing additional output formats to file.
  changelog.d/saf-341.added
  cli/src/semgrep/commands/ci.py
  cli/src/semgrep/commands/scan.py
  cli/src/semgrep/output.py
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs/emacs.txt.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs/gitlab_sast.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs/gitlab_secrets.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs/one.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs/sarif.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs/text.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs/two.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs/vim.txt.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--emacs/result.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--emacs/result.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--gitlab-sast/result.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--gitlab-sast/result.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--gitlab-secrets/result.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--gitlab-secrets/result.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--json/result.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--json/result.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--sarif/result.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--sarif/result.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--vim/result.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_flag/--vim/result.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--emacs/result.out.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--emacs/sarif.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--gitlab-sast/result.out.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--gitlab-sast/sarif.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--gitlab-secrets/result.out.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--gitlab-secrets/sarif.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--json/result.out.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--json/sarif.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--sarif/result.out.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--sarif/sarif.json.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--vim/result.out.expected
  cli/tests/default/e2e/snapshots/test_output/test_additional_outputs_with_format_output_flag/--vim/sarif.json.expected
  cli/tests/default/e2e/test_output.py
  src/osemgrep/cli_scan/Scan_CLI.ml
Labels: wait-for-me

#10134 chore: be more verbose about rule downloading
  src/osemgrep/language_server/notifications/Notification_handler.ml
  src/osemgrep/language_server/server/Session.ml
  src/osemgrep/language_server/server/Session.mli
Labels: wait-for-me

#10145 fix: send notification when rules have refreshed
  src/osemgrep/language_server/Test_LS_e2e.ml
  src/osemgrep/language_server/scan_helpers/Scan_helpers.ml
  src/osemgrep/language_server/scan_helpers/dune
  src/osemgrep/language_server/server/RPC_server.ml
  src/osemgrep/language_server/server/RPC_server.mli
  src/osemgrep/language_server/server/User_settings.ml
Labels: wait-for-me

#9987 chore(secrets): modify secrets flags for ci and scan commands
  changelog.d/gh-9987.changed
  cli/src/semgrep/commands/ci.py
  cli/src/semgrep/commands/scan.py
  src/osemgrep/cli_ci/Ci_CLI.ml
  src/osemgrep/cli_scan/Scan_CLI.ml
  src/osemgrep/cli_scan/Scan_CLI.mli
Labels: Do not merge
